== Hashicorp Vault Secrets Retrieval and Refresh with Apache Camel On OCP

First of all all of the following could be supported by simply adding
the camel-hashicorp-vault component to your classpath.

To set up the secret retrieval with Azure Key Vault you have to
first authenticate to the Hashicorp Vault Service. The mechanisms are:

Static credentials in application.properties:

....
camel.vault.hashicorp.token = token
camel.vault.hashicorp.host = host
camel.vault.hashicorp.port = port
camel.vault.hashicorp.scheme = scheme
....

Once we have the Hashicorp Vault instance running or an Hashicorp Vault instance to point to we can create the secret via vault cli

....
vault kv put secret/authsecdb username="username" password="password" host="host"
....

The secret name will be authsecdb and the secret fields will be username, password and host. The Secret engine will be secret in this case.

In the Camel route it will be enough to use the following syntax and the secrets field will be retrieved.

....
{{hashicorp:secret:authsecdb/host}}
{{hashicorp:secret:authsecdb/username}}
{{hashicorp:secret:authsecdb/password}}
....

The same configuration could be seen on OCP by following the Camel on
OCP Best Practices repository, in particular, the Hashicorp vault section. You
can follow the example for both the runtimes supported by Red Hat Build
of Apache Camel:

https://github.com/oscerd/camel-on-ocp-best-practices/tree/main/vault/hashicorp-vault/camel-quarkus/retrieval[Camel-Quarkus
- Camel on OCP Best practices - Camel Quarkus - Hashicorp Vault]

https://github.com/oscerd/camel-on-ocp-best-practices/tree/main/vault/hashicorp-vault/camel-spring-boot/retrieval[Camel-Quarkus
- Camel on OCP Best practices - Camel Spring Boot - Hashicorp Vault]
